# Generated by Django 2.2.2 on 2019-07-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AminoAcid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('txt', models.FileField(upload_to='AminoAcid/fasta/')),
                ('host', models.CharField(max_length=20)),
                ('host_threshold', models.CharField(max_length=20)),
                ('gc_richness_threshold', models.CharField(max_length=20)),
                ('gc_richness_chunk_size', models.CharField(max_length=20)),
                ('host_profile', models.CharField(max_length=20)),
                ('local_homopolymer_threshold', models.CharField(max_length=20)),
                ('cycles', models.CharField(max_length=20)),
                ('inner_cycles', models.CharField(max_length=20)),
                ('max_relax', models.CharField(max_length=20)),
                ('restriction_sites', models.CharField(max_length=200)),
                ('remove_splice_sites', models.CharField(max_length=20)),
                ('remove_alternate_start_site', models.CharField(max_length=20)),
                ('result', models.FileField(blank=True, null=True, upload_to='AminoAcid/fasta/')),
            ],
        ),
    ]
