# Generated by Django 2.2.2 on 2019-07-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aminoacid',
            name='host_profile',
        ),
        migrations.RemoveField(
            model_name='aminoacid',
            name='remove_alternate_start_site',
        ),
        migrations.RemoveField(
            model_name='aminoacid',
            name='remove_splice_sites',
        ),
        migrations.RemoveField(
            model_name='aminoacid',
            name='restriction_sites',
        ),
        migrations.RemoveField(
            model_name='aminoacid',
            name='result',
        ),
        migrations.RemoveField(
            model_name='aminoacid',
            name='title',
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='input',
            field=models.CharField(default='input.fasta', max_length=20),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='local_host_profile',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='one_line_fasta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='output',
            field=models.CharField(blank=True, default='out.fasta', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='restriction_enzymes',
            field=models.CharField(blank=True, default=['NdeI', 'XhoI', 'HpaI', 'PstI', 'EcoRV', 'NcoI', 'BamHI'], max_length=200),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='run',
            field=models.BooleanField(blank=True, default=True, editable=False),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='splice_sites',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='start_sites',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='verbose',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aminoacid',
            name='cycles',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='aminoacid',
            name='gc_richness_chunk_size',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='aminoacid',
            name='gc_richness_threshold',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='aminoacid',
            name='host',
            field=models.CharField(blank=True, default='413997', max_length=20),
        ),
        migrations.AlterField(
            model_name='aminoacid',
            name='host_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='aminoacid',
            name='inner_cycles',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='aminoacid',
            name='local_homopolymer_threshold',
            field=models.IntegerField(blank=True, default=4),
        ),
        migrations.AlterField(
            model_name='aminoacid',
            name='max_relax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='aminoacid',
            name='txt',
            field=models.FileField(null=True, upload_to='AminoAcid/fasta/'),
        ),
    ]
