# Generated by Django 2.2.2 on 2019-08-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20190730_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aminoacid',
            name='verbose',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
