# Generated by Django 2.2.2 on 2019-09-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20190802_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aminoacid',
            name='input',
        ),
        migrations.AlterField(
            model_name='aminoacid',
            name='host_threshold',
            field=models.FloatField(blank=True, default=0.1),
        ),
        migrations.AlterField(
            model_name='aminoacid',
            name='max_relax',
            field=models.FloatField(blank=True, default=0.1),
        ),
    ]
