# Generated by Django 2.2.2 on 2019-10-12 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_auto_20190914_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aminoacid',
            old_name='gc_richness_threshold',
            new_name='gc_richness_max',
        ),
        migrations.RenameField(
            model_name='aminoacid',
            old_name='cycles',
            new_name='max_generation',
        ),
        migrations.RemoveField(
            model_name='aminoacid',
            name='inner_cycles',
        ),
        migrations.RemoveField(
            model_name='aminoacid',
            name='local_homopolymer_threshold',
        ),
        migrations.RemoveField(
            model_name='aminoacid',
            name='max_relax',
        ),
        migrations.RemoveField(
            model_name='aminoacid',
            name='one_line_fasta',
        ),
        migrations.RemoveField(
            model_name='aminoacid',
            name='output',
        ),
        migrations.RemoveField(
            model_name='aminoacid',
            name='result',
        ),
        migrations.RemoveField(
            model_name='aminoacid',
            name='run',
        ),
        migrations.RemoveField(
            model_name='aminoacid',
            name='verbose',
        ),
    ]
